### ISSUE TITLE
关于viewport问题

### ISSUE THREAD

**Issue by CoderIvan** [huruji/FE-Interview#5]
所参考的文章，描述的太乱了，不建议阅读

建议使用以下文章

> http://weizhifeng.net/viewports.html

> http://weizhifeng.net/viewports2.html

**Comment by huruji** [comment]
嗯，谢谢，提一个PR吧，merge一下

**Comment by huruji** [comment]
@CoderIvan

**Comment by CoderIvan** [comment]
好的，稍后提
